### ISSUE TITLE
no implicit conversion of Hash into Integer (TypeError) 	

### ISSUE THREAD

**Issue by Kolekar** [TrestleAdmin/trestle-auth#31]
While executing `rails generate trestle:auth:install User --devise` throws following error

```
/Users/harikesh.kolekar/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:860:in` `block in result': no implicit conversion of Hash into Integer (TypeError)
	from /Users/harikesh.kolekar/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:862:in `result'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/trestle-auth-0.4.0/lib/generators/trestle/auth/install/install_generator.rb:54:in `template_content'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/trestle-auth-0.4.0/lib/generators/trestle/auth/install/install_generator.rb:21:in `block in insert_configuration'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/actions/inject_into_file.rb:48:in `initialize'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/actions/inject_into_file.rb:32:in `new'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/actions/inject_into_file.rb:32:in `insert_into_file'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/trestle-auth-0.4.0/lib/generators/trestle/auth/install/install_generator.rb:20:in `insert_configuration'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/railties-5.0.7.2/lib/rails/generators.rb:180:in `invoke'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/railties-5.0.7.2/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/harikesh.kolekar/harry/call_center/bin/rails:9:in `<top (required)>'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/harikesh.kolekar/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/harikesh.kolekar/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/harikesh.kolekar/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
harikeshk-mbp:call_center harikesh.kolekar$ 

```

**Comment by spohlenz** [comment]
This should hopefully now be fixed in 021955a. The issue was related to older Ruby versions (< 2.6).
